### ISSUE TITLE
Pressing + or open inventory near a dungeon up/down glitches

### ISSUE THREAD

**Issue by erfg12** [lantus/devilution-nx#19]
All sorts of weird glitches happen when you open inventory or press + near the dungeon up/down staircases.

Most of the time it makes my character invisible and disables movement.

An easy temporary fix would be to detect if you're near a staircase and disable all button presses except for movement. But, that wouldn't be a good permanent fix.

**Comment by erfg12** [comment]
A possible fix might be to go into the ``LoadGameLevel`` function and on the first line add:

```
if (invflag || spselflag)
    return;
```

Untested, just an idea.

**Comment by rsn8887** [comment]
I just made a PR to fix this. It was trivial in the end.
