### ISSUE TITLE
Initial Launch crashes

### ISSUE THREAD

**Issue by erfg12** [lantus/devilution-nx#2]
Initial game launch crashes console. After reboot it works fine. Is it because Diablo.ini isn`t initially created?

**Comment by soulthunk** [comment]
I'm gonna call it yes, drop the .ini in before initial boot and it should work right. Don't have a switch to test it on, so it may not work. Just a thought.

**Comment by lantus** [comment]
make sure the MPQ does not have read only permissions and retry. I've never been able to reproduce this issue

**Comment by rsn8887** [comment]
I cannot reproduce this either. Can you re-confirm this issue and how to reproduce? Did you maybe use album to launch? (always hold R on a game to launch homebrew, never album)

**Comment by erfg12** [comment]
Yeah, it could have been because of launching from album.
