### ISSUE TITLE
Pressing a button immediately after a level transition will cause an immediate level skip which you cannot escape from

### ISSUE THREAD

**Issue by juraisa** [lantus/devilution-nx#21]
I tested this in devilution-nx initial release (0.9) as well as 0.92, 0.94, and compiling from latest available code and it happens in every build.

If you immediately press a button such as A right after going down or up a set of stairs, you immediately transition to the next floor forwards or backwards, depending on which direction you were going, but your character is not in your view port and you are essentially softlocked unless you load a save.

I haven't used devilution on PC so I don't know if it's some debug feature in the base code, cursory glance at erfg12's pc controller fork and devilutionX at commits and issues I didn't immediately see anything mentioning this issue so can't really tell if it came from changes here or elsewhere. 

Made a couple new characters and could replicate every time, I'm using the MPQ from an original diablo disc if it makes any difference.

**Comment by rsn8887** [comment]
I just made a PR to fix this.
