### ISSUE TITLE
up/down/left/right hard to press

### ISSUE THREAD

**Issue by erfg12** [lantus/devilution-nx#3]
Using the left joycon up/down/left/right are difficult to get. The diagnols seem to be hit 90% of the time.

**Comment by Svahnen** [comment]
I experience this as well.
To clarify, its when trying to walk horizontally or vertically that the problem occurs, since it is hard to hit the diagonal axis with the joystick. At the moment I have to be very precise when trying to hit for example left and up at the same time with the joystick.

**Comment by erfg12** [comment]
It's probably due to this change that was made - https://github.com/lantus/devilution-nx/commit/269c2f4f7cb40fdb4e7acda06c809faea79b3bb2#diff-7764fcf847f81aaab1cbc478ed9bfd3d

**Comment by erfg12** [comment]
Fixed in PR https://github.com/lantus/devilution-nx/pull/10
