### ISSUE TITLE
No input at all

### ISSUE THREAD

**Issue by acheronfail** [lantus/devilution-nx#30]
Sorry for making an issue, but I've been struggling to fix this.

When I run this the game opens, sound plays, and it takes me to the menu, but it seems I can't input anything at all (pressing any/all buttons does absolutely nothing).

I'm using version `0.95` of this package, and am running `10.1.0|AMS 0.13.0` on my switch...

Do you have any pointers for me?

**Comment by acheronfail** [comment]
I compiled from source and this issue disappeared. :man_shrugging: No idea why it doesn't work from the release download!

**Comment by rsn8887** [comment]
You should really use the latest official
Switch version because this project code has been upstreamed a long time ago and many bugs have been fixed:
https://github.com/diasurgical/devilutionX/releases/latest

**Comment by AJenbo** [comment]
For one thing the save games in 0.95 are invalid

**Comment by acheronfail** [comment]
@rsn8887 @AJenbo thanks for getting back to me so quickly on this issue! 😆 

I tried building diasurgical/devilutionX first before this one, but I couldn't get it to compile for the life of me. I found this repository, and first try it compiled beautifully so that's why I used this one. 😅 

Maybe I'll have another crack at diasurgical/devilutionX, but I had a good crack at it and couldn't get it working at all.

**Comment by rsn8887** [comment]
To compile the diasurgical/devilutionX version for now, make sure you pull this commit as well: 
https://github.com/diasurgical/devilutionX/pull/764

Then do this from above the devilutionX directory:
```
mkdir buildswitch
cd buildswitch
cmake ../devilutionX -DBINARY_RELEASE=ON -DNONET=ON -DCMAKE_TOOLCHAIN_FILE=../devilutionX/CMake/switch/devkita64-libnx.cmake
make
```
