### ISSUE TITLE
diablo-nx not launching in Yuzu (tracking issue)

### ISSUE THREAD

**Issue by heinermann** [lantus/devilution-nx#31]
Since I'm making commits to [Yuzu](https://github.com/yuzu-emu/yuzu) (Switch emulator) I will be looking into this. For context I think it will be easier to debug from this side than emulator-side. I'll create a sister issue for them as well once I figure out how to compile and rule out anything dumb such as not checking the right directory.

## Steps
1. Copied `DIABDAT.MPQ` and contents of `diablo-nx.zip` to `AppData\Roaming\yuzu\sdmc\switch\diablo-nx`.
2. In Yuzu (master), File -> Load File... -> `diablo-nx.nro`.
3. Yuzu shows loading bar for 1s, followed by game immediately closing back to the rom list.

## Notes
- Does create a `diablo.ini` in `yuzu\sdmc`, so it is doing something before closing.

## Issues
- [ ] NRO game title/header metadata is missing.
- [ ] Game immediately closes.

**Comment by AJenbo** [comment]
Switch support has been up streamed and is being maintained there: https://github.com/diasurgical/devilutionX it has both multiplayer, widescreen and 60fps support and should work with the emulators as well.
